# Generated by Django 5.1.7 on 2025-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCampus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='banners/一秒上瘾的小众英文歌_109951165055862669.jpg', upload_to='banners/')),
                ('order', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': '欢迎表'},
        ),
        migrations.AlterField(
            model_name='welcome',
            name='img',
            field=models.ImageField(default='welcome/OIP-C.jpg', upload_to='welcome/'),
        ),
    ]
