# Generated by Django 5.1.7 on 2025-04-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCampus', '0003_notices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='welcome/OIP-C.jpg', upload_to='avatar/')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[('1', '男'), ('2', '女'), ('0', '保密')], verbose_name='性别')),
                ('introduction', models.TextField(max_length=100, verbose_name='简介')),
                ('wechat_openid', models.CharField(max_length=100, verbose_name='openId')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.RemoveField(
            model_name='notices',
            name='text',
        ),
        migrations.AddField(
            model_name='notices',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('views', models.IntegerField(default=0, verbose_name='浏览')),
                ('likes', models.IntegerField(default=0, verbose_name='喜欢')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartCampus.comments', verbose_name='评论')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartCampus.user', verbose_name='发布者')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_avatar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_avatar', to='smartCampus.user', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='comments',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='smartCampus.user', verbose_name='评论者'),
        ),
    ]
