# Generated by Django 5.1.7 on 2025-04-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCampus', '0004_comments_user_remove_notices_text_notices_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_avatar',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_avatar', to='smartCampus.user', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commenter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='smartCampus.user', verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(default=0, max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='smartCampus.comments', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartCampus.user', verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=0, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[('1', '男'), ('2', '女'), ('0', '保密')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default=0, max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=10, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(default=0, max_length=100, verbose_name='openId'),
        ),
    ]
