# Generated by Django 5.1.7 on 2025-04-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCampus', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (0, '保密')], verbose_name='性别'),
        ),
    ]
