# Generated by Django 5.1.7 on 2025-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCampus', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='img',
            field=models.ImageField(default='on.jpg', upload_to='welcome/'),
        ),
    ]
