# Generated by Django 5.1.7 on 2025-04-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCampus', '0009_alter_welcome_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcome',
            options={},
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='order',
        ),
        migrations.AlterField(
            model_name='welcome',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='img',
            field=models.ImageField(upload_to='welcome/on.jpg', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
