# Generated by Django 5.1.7 on 2025-04-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartCampus', '0011_alter_banners_managers_alter_comments_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
    ]
