# Generated by Django 5.1.7 on 2025-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartCampus', '0013_alter_banners_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='order',
        ),
        migrations.AlterField(
            model_name='banners',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
